version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # 👈 host:container — avoid conflict with native Postgres
    environment:
      - POSTGRES_DB=chaiDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
